slack:
  channel: "random"
  username: "Delivery Bot"
  notify:
    - "<@UDKQ8R6H1>"
  webhook: "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVERLVDI0NkpXL0IwMTE1SEhLVVQwL1JuZzAzMWZvelBpNHVxV1pnZ0RqclhZUQo"
asda:
  on: false
  rate: 1
iceland:
  on: true
  rate: 5