slack:
  channel: "random"
  username: "Delivery Bot"
  notify:
    - ""  # From slack you can set users in here to notify, this looks like <@UDKQ8R6H1>
  webhook: "" # Setup a webhook on slack put in here
asda:
  on: true
  rate: 1
  url: "https://groceries.asda.com/api/v3/slot/view"
  postcode: ""  # Set your postcode so that Asda will find your nearest store
  accountId: ""  # This is your asda account ID
  autoPlaceOrder: false
    slotDate: ""  # Earliest date to check for delivery slots, if empty then current date
iceland:
  on: false
  rate: 5
  url: "https://www.iceland.co.uk/book-delivery"
  postcode: ""  # Set your postcode so that Iceland will find your nearest store
