apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-notifications-1
  labels:
    app: delivery-notifications
    release: delivery-notifications-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: delivery-notifications-1
  template:
    metadata:
      labels:
        app: delivery-notifications
        name: delivery-notifications-1
        release: delivery-notifications-dev
    spec:
      containers:
      - name: delivery-notifications
        image: "krisawatson/delivery-notifications:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
